= Deploy your first Serverless application

The sample code in this section helps you to deploy your first Serverless workload using https://github.com/knative/docs/tree/master/serving[Knative-Serving]

This repo folder has sources for Java and Node.

== Building and Deploying Application

The source folder **part-1** will be referred as `$PROJECT_HOME`. The following section details on how to build either Java or Node Application.

=== Java

[source,bash]
----
cd $PROJECT_HOME/java
./mvnw jib:dockerBuild # <1>
----
<1> this should build a image like `dev.local/greeter:0.0.1-SNAPSHOT`

=== Node

[source,bash]
----
cd $PROJECT_HOME/node

docker build -t dev.local/greeter:0.0.1-SNAPSHOT --rm . # <1>
----
<1> this should build a image like `dev.local/greeter:0.0.1-SNAPSHOT`

=== Deploying Service

[source,bash]
----
cd $PROJECT_HOME
kubectl -f service.yaml
----

== Useful commands

The following are some useful commands

- Get all **Knative services** on project **myproject** `kubectl -nmyproject get service.serving.knative.dev`
- Get all **Knative configurations** on project **myproject** `kubectl -nmyproject get configuration.serving.knative.dev`
- Get all **Knative routes** on project **myproject** `kubectl -nmyproject get route.serving.knative.dev`
- Get all **Knative revisions** on project **myproject** `kubectl -nmyproject get revision.serving.knative.dev`

[TIP]
====
If you need to get the specific service,configuration,route or revision etc., the add the name to the end of the commands above
e.g to get a service named **foo**:

`kubectl -nmyproject get service.serving.knative.dev foo`
====