apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: customer
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/customer:0.0.1
            env:
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
