:experimental:

= Build your Kubernetes Serverless Service

The sample code in this section helps you to deploy serverless workload using https://github.com/knative/docs/tree/master/serving[Knative-Serving] following source to container strategy. 

This demo shows how to build the container using  https://buildah.io[buildah]

== Pre-requisite

- https://github.com/knative/docs/blob/master/build/installing-build-component.md[Knative Build] is installed
- Basic knowledge of how to build container images with https://buildah.io[buildah]

=== User namespaces
By default RHEL/Centos sets the max_user_namespaces value to **0**, you need to set that to bigger value to make the buildah container builds to pass, set the `max_user_namespaces` kernel parameter to 15000. For more details on user namespaces refer to http://man7.org/linux/man-pages/man7/user_namespaces.7.html

[source,bash]
----
minishift ssh
sudo -i 
echo 15000 > /proc/sys/user/max_user_namespaces
----

=== Skipping tag to digest
The Knative-serving is by default skips tag to digest for the registries `ko.local` and `dev.local`, as part of this demo you will push the build image to internal default docker registry (__docker-registry.default.svc:5000__) , you will need update `registriesSkippingTagResolving` attribute of the config-controller ConfigMap to include the registry **docker-registry.default.svc:5000** to be skipped for tag to digest resolving.

[source,bash]
----
val=$(oc -n knative-serving get cm config-controller -oyaml | yq r - data.registriesSkippingTagResolving | awk '{print $1",docker-registry.default.svc:5000"}')
oc -n knative-serving get cm config-controller -oyaml | yq w - data.registriesSkippingTagResolving $val | oc apply -f -  
----

== Building and Deploying Application

The source folder **part-2** will be referred as `$PROJECT_HOME`. The following section details on how to build either Java or Node Application.

=== Building 

The application uses Knative-build to build the application.

==== Apply Build Template

[source,bash]
----
cd $PROJECT_HOME/build
oc apply -f templates/java-buildah-template.yaml # #<1>
oc apply -f m2-pvc.yaml # #<2>
----

<1> The template that will be build the container from sources 
<2> A persistence volume is configured to store .m2 repository and o make the subsequent maven builds faster

=== Deploying Service

[source,bash]
----
cd $PROJECT_HOME
oc apply -f service.yaml
----

=== Invoking Service

[source,bash]
----
cd $PROJECT_HOME
bin/call.sh
----

== Clean up

Clean up all the resources created as part of this demo,

[source,bash]
----
oc delete configurations.serving.knative.dev --all
oc delete buildtemplate.build.knative.dev --all
oc delete is greeter
----

== Useful commands

The following are some useful commands

- Get all **Knative services** on project **myproject** `kubectl -nmyproject get service.serving.knative.dev`
- Get all **Knative configurations** on project **myproject** `kubectl -nmyproject get configuration.serving.knative.dev`
- Get all **Knative routes** on project **myproject** `kubectl -nmyproject get route.serving.knative.dev`
- Get all **Knative revisions** on project **myproject** `kubectl -nmyproject get revision.serving.knative.dev`
- Get all **Knative builds** on project **myproject** `kubectl -nmyproject get builds.build.knative.dev`
- Get all **Knative build templates** on project **myproject** `kubectl -nmyproject get buildtemplates.build.knative.dev`

[TIP]
====
If you need to get the specific service,configuration,route or revision etc., the add the name to the end of the commands above
e.g to get a service named **foo**:

`kubectl -nmyproject get service.serving.knative.dev foo`
====
