= Route to your Serverless service

The sample code in this section helps you to configure https://github.com/knative/docs/tree/master/serving[Knative-Serving] routes and perform the traffic splitting

This repo folder has sources for Java and Node.

== Building and Deploying Application

The source folder **part-1** will be referred as `$PROJECT_HOME`. The following section details on how to build either Java.

=== Java

[source,bash]
----
cd $PROJECT_HOME/java
./mvnw jib:dockerBuild # <1>
----
<1> this should build a images like `dev.local/customer:0.0.1`,`dev.local/preference:0.0.1`,`dev.local/recommendation:0.0.1`


=== Deploying Service

[source,bash]
----
cd $PROJECT_HOME
----

== Useful commands

The following are some useful commands

- Get all **Knative services** on project **myproject** `kubectl -nmyproject get service.serving.knative.dev`
- Get all **Knative configurations** on project **myproject** `kubectl -nmyproject get configuration.serving.knative.dev`
- Get all **Knative routes** on project **myproject** `kubectl -nmyproject get route.serving.knative.dev`
- Get all **Knative revisions** on project **myproject** `kubectl -nmyproject get revision.serving.knative.dev`

[TIP]
====
If you need to get the specific service,configuration,route or revision etc., the add the name to the end of the commands above
e.g to get a service named **foo**:

`kubectl -nmyproject get service.serving.knative.dev foo`
====